In [2]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable


# We are going to learn numpy now!


In [3]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,2,5]])

In [6]:
type(arr)

numpy.ndarray

In [8]:
#printing no. of dimensions in an array
print("dimensions:", arr.ndim)

#printing shape of array
print("shape:",arr.shape)

#size of array
print("size:",arr.size)

#print type of elements in array
print("array stores elements of type:",arr.dtype)




dimensions: 2
shape: (2, 3)
size: 6
array stores elements of type: int32


# Ways of creating array

In [8]:
#creating array from list with type float
a = np.array([[1,3,4],[5,6,7]],dtype = 'float')
print("Array created using passed list:\n",a)

#creating array from tuple
b = np.array((1,3,2))
print("\nArray created using passed tuple:\n",b)

#creating a 3X4 array with all zeros
c = np.zeros((3,4))
print("\nArray insitialized with all zeros:\n",c)

#creating a constant value array of complex type
d = np.full((3,3),6, dtype = 'complex')
print("\nAn array initialised with all 6s.Array type is complex:\n",d)

#creating array with random value
e = np.random.random((2,2))
print("\nA random array:\n",e)


Array created using passed list:
 [[1. 3. 4.]
 [5. 6. 7.]]

Array created using passed tuple:
 [1 3 2]

Array insitialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialised with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.52616776 0.56495771]
 [0.29618924 0.35444889]]


In [5]:
#identity matrix 3X3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [7]:
#creating sequence of integers from 0 to 30 with step of 5
f = np.arange(0,30,5)
print("\nA sequential array with steps of 5:\n", f)

#creating a sequence of 10 value in range 0 to 5
g = np.linspace(0,5,10)
print("nA sequential array with 10 values between 0 and 5:\n", g)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]
nA sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [13]:
#reshaping array 3X4 array to 2X2X3 array
arr = np.array([[1,2,3,4],
                [5,3,4,2],
                [2,7,8,9]])
newarr = arr.reshape(2,2,3)
print("original array:\n",arr)
print("reshaped array:\n",newarr)

original array:
 [[1 2 3 4]
 [5 3 4 2]
 [2 7 8 9]]
reshaped array:
 [[[1 2 3]
  [4 5 3]]

 [[4 2 2]
  [7 8 9]]]


In [14]:
#flatten entire array into a single object
arr = np.array([[1,2,3],[4,5,6]])
flat = arr.flatten()
print("original array:\n",arr)
print("flattened array:\n",flat)

original array:
 [[1 2 3]
 [4 5 6]]
flattened array:
 [1 2 3 4 5 6]


# Array Indexing


In [15]:
arr = np.array([[-1,2,3,4],
                [4,-.5,6,0],
                [2.6,0.,6.,0.],
                [3.,-7,4.,2.]])

In [17]:
arr[1::2,:3:2]

array([[4., 6.],
       [3., 4.]])

In [18]:
#bolean array indexing 
condition = arr > 0
temp = arr[condition]
print("elements greater than 0:\n",temp)

elements greater than 0:
 [2.  3.  4.  4.  6.  2.6 6.  3.  4.  2. ]


In [19]:
 a = np.array([1,2,5,3])

#add 1 to every element
print("adding 1:",a+1)

#subtract 3 from elements
print("subtract 3:",a-3)

#multiply each element by 10
print("multiplying each element by 10:",a*10)

#squaring each element
print("squaring elements:",a**2)

#modify existing array
a *= 2
print("doubled each element of original array:",a)

#transpose of array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\noriginal array:\n",a)
print("Transpose array:\n",a.T)

adding 1: [2 3 6 4]
subtract 3: [-2 -1  2  0]
multiplying each element by 10: [10 20 50 30]
squaring elements: [ 1  4 25  9]
doubled each element of original array: [ 2  4 10  6]

original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
arr = np.array([[1,5,6],
               [4,7,2],
                [3,1,9]])
#maximum elements of array
print("Largest element is:",arr.max())
print("row-wise maximum element:",arr.max(axis = 1))

#minimum element of arrat
print("column-wise maximum element:",arr.max(axis = 0))


Largest element is: 9
row-wise maximum element: [6 7 9]
column-wise maximum element: [4 7 9]


In [22]:
#sum of array elements
print("sum of all array element:",arr.sum())

#cumulative sum along each row
print("cumulative sum of all array element:\n",arr.cumsum(axis = 1))



sum of all array element: 38
cumulative sum of all array element:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [23]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[4,3],
              [2,1]])

#adding two array
print("array sum :\n",a+b)

#multiply array elementwise multiplication
print("array multiplication:\n",a*b)

#matrix multiplication
print("matrix multiplication:\n",a.dot(b))

array sum :
 [[5 5]
 [5 5]]
array multiplication:
 [[4 6]
 [6 4]]
matrix multiplication:
 [[ 8  5]
 [20 13]]


In [25]:
#create array of sine value
# a = np.array([0,np.pi/2,np.pi])
# print("sine values :", np.sine(a))

#exponential values
a = np.array([0,1,2,3])
print("exponent of array elements:",np.exp(a))

#square root 
print("square root :",np.sqrt(a))

exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
square root : [0.         1.         1.41421356 1.73205081]


# Sorting array

In [26]:
a = np.array([[1,4,2],
              [3,4,6],
              [0,-1,5]])
#sorted array 
print("sorted array:\n",np.sort(a,axis = None))

#sort row-wise
print("row-wise sorted array:\n",np.sort(a,axis = 1))

#specify sort algorithm
print("column wise sort by applying merge-sort:\n",np.sort(a,axis =0 ,kind = 'mergesort'))

sorted array:
 [-1  0  1  2  3  4  4  5  6]
row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


# Stacking and splitting

In [28]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
#vertical stacking 
print("Vertical stacking:\n",np.vstack((a,b)))

#horizontal stacking
print("\nHorizontal stacking:\n",np.hstack((a,b)))

c = [5,6]
#stacking columns
print("\n column stacking:\n", np.column_stack((a,c)))


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

 column stacking:
 [[1 2 5]
 [3 4 6]]


In [29]:
#concatenation method
print("concatenating to 2nd axis:\n",np.concatenate((a,b),1))

concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [30]:
a = np.array([[1,2,3,4,5,6],
              [2,5,8,9,7,4]])
#horizontal splitting
print("splitting along horizontal axis into 2 parts:\n",np.hsplit(a,2))

#vertical splitting
print("\nsplitting along vertical axis into 2 parts:\n",np.vsplit(a,2))
             


splitting along horizontal axis into 2 parts:
 [array([[1, 2, 3],
       [2, 5, 8]]), array([[4, 5, 6],
       [9, 7, 4]])]

splitting along vertical axis into 2 parts:
 [array([[1, 2, 3, 4, 5, 6]]), array([[2, 5, 8, 9, 7, 4]])]
