# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [12]:
print("NumPy version:" ,np.__version__)
print("\nConfiguration:",np.show_config())

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

#### 3. Create a null vector of size 10

In [16]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [22]:
memory_size = null_vector.nbytes
print(f"memory size:{memory_size} bytes")

memory size:80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [27]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [23]:
null_vect = np.zeros(10)
null_vect[4] = 1
print(null_vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [26]:
a = np.arange(10,50)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [31]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
b = np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [8]:
c = np.array([1,2,0,0,4,0])
nonzeros_element = np.nonzero(c)
print(nonzeros_element)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [10]:
d = np.random.random((3,3,3))
print(d)

[[[0.88807333 0.0377396  0.25558112]
  [0.49142502 0.15789687 0.31372241]
  [0.11114964 0.49224644 0.12989747]]

 [[0.51764058 0.05410266 0.55548035]
  [0.43965874 0.41919985 0.50201093]
  [0.56666392 0.65094956 0.37423831]]

 [[0.36164798 0.15646799 0.34364931]
  [0.57207421 0.05229514 0.86018918]
  [0.26145951 0.66446071 0.14564602]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
random_array = np.random.random((10,10))
print(random_array)
print("\nMaximum value is:",random_array.max())
print("\nMinimum value is:",random_array.min())

[[0.69999239 0.8768197  0.30560864 0.1986254  0.7921144  0.81353089
  0.53394162 0.29602873 0.57549432 0.64494596]
 [0.27299138 0.21775701 0.60067927 0.27596203 0.53434089 0.60383295
  0.12715879 0.01536509 0.6639388  0.38443551]
 [0.34020544 0.50150114 0.5258034  0.27023455 0.93098686 0.65313554
  0.05750716 0.35184166 0.6820021  0.75890495]
 [0.07689736 0.37480641 0.34722823 0.56631235 0.59859126 0.28676978
  0.16220789 0.34914638 0.90135329 0.24111361]
 [0.6251995  0.80831498 0.73710131 0.31033294 0.92820875 0.5401182
  0.83961542 0.35565712 0.47755168 0.14021111]
 [0.66264237 0.74202271 0.66663268 0.70308463 0.64696029 0.20039144
  0.24683941 0.05465963 0.93228694 0.50261393]
 [0.08649871 0.31028879 0.71504896 0.90795327 0.39520965 0.04033706
  0.72118739 0.54576959 0.42845257 0.94920031]
 [0.54981079 0.31513832 0.25300542 0.22894943 0.21530057 0.9645721
  0.32714366 0.79154356 0.64247224 0.81940467]
 [0.89088472 0.23012312 0.42353454 0.92132718 0.11614444 0.49735443
  0.90832282 0

#### 14. Create a random vector of size 30 and find the mean value

In [19]:
e = np.random.random(30)
mean_value = np.mean(e)
print("random vector:",e)
print("\nMean value:",mean_value)

random vector: [0.13812799 0.44156377 0.24525122 0.1509919  0.20209879 0.32266024
 0.54471044 0.29623411 0.1028404  0.24511482 0.8815846  0.53732597
 0.99725117 0.87891847 0.83392775 0.41229968 0.651923   0.46832425
 0.77306655 0.9129824  0.39712828 0.90263318 0.07637988 0.03014043
 0.58281819 0.30293419 0.92414263 0.24386972 0.77107188 0.34061463]

Mean value: 0.4869643510442367


#### 15. Create a 2d array with 1 on the border and 0 inside

In [21]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [24]:
arr = np.ones((5,5))
padded_array = np.pad(arr,pad_width=1,mode ='constant',constant_values=0)
print(padded_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

1.nan #anthing multipled by nan(not a number) will be nan only 
2.false #in IEEE floating-point arithmetic, nan is not considered equal to anything, including itself. So, the comparison returns False
3.false #Comparisons involving nan always return False 
4.nan #Any arithmetic operation involving nan results in nan 
5.True #np.nan is in the set [np.nan],so it returns True 
6.false #This is due to floating-point precision errors. In most systems, 3 * 0.1 doesn't exactly equal 0.3 

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [26]:
# we use diag function for diagonal operations 
#k=0 means main diagonal
#k=-1 means diagonal below main digonal
#k=1 means diagonal above main diagonal
value = np.array([1,2,3,4])
matrix = np.diag(value,k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [28]:
checkerboard = np.zeros((8,8),dtype=int)
checkerboard[1::2,::2]=1 # odd rows even column
checkerboard[::2,1::2]=1 #even rows odd column
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [30]:
shape = (6,7,8)
linear_index = 99 #index for 100th element will  be 99 because array is 0 indexed
multi_index = np.unravel_index(linear_index,shape)
print(multi_index)

(1, 5, 3)
